name: score_bot
description: Application mobile de scoring en temps réel par commande vocale.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # State management & DI
  provider: ^6.1.2
  get_it: ^8.0.3

  # Navigation
  go_router: ^14.6.2

  # Stockage local
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Audio recording & Local Speech
  record: ^6.1.2
  speech_to_text: ^7.4.0
  path_provider: ^2.1.5
  path: ^1.9.0

  # Permissions
  permission_handler: ^11.3.1

  # HTTP & API
  http: ^1.2.2

  # Utilities
  intl: ^0.20.0
  uuid: ^4.5.1
  equatable: ^2.0.7
  flutter_localizations:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1

  # Environnement variables
  flutter_dotenv: ^6.0.1
  share_plus: ^13.3.0
  flutter_tts: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  default-flavor: phone
  generate: true
  uses-material-design: true
  assets:
    - .env
